name: KnapsackToGo
main: cn.jji8.KnapsackToGo.main
version: 5.5
author: jianjianai
softdepend: [Vault]
api-version: 1.13
commands:
  保存背包:
    aliases: [bcbb, baocunbeibao]
    description: "保存背包的命令"
    permission: 跨服背包.保存背包
    permission-message: "你没有权限执行此命令"
    usage: /<command>
  加载背包:
    aliases: [jzbb, jiazaibeibao]
    description: "加载背包的命令"
    permission: 跨服背包.加载背包
    permission-message: "你没有权限执行此命令"
    usage: /<command>
  解锁:
    aliases: [js, jiesuo]
    description: "加载背包的命令"
    permission: 跨服背包.解锁
    permission-message: "你没有权限执行此命令"
    usage: /<command> 玩家名